name: OiltoSun
favicon: null
layout_spectrum: 0.37723396299406886
typography_spectrum: 0.23607708094641566
title: 'Tech & Energy Ramblings'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b6ccf1'
    - '#1a2452'
    - '#4f72bf'
    - '#fefefe'
  brandStrength: 0.5
  lightness: 0.4895909421611577
  saturation: 0.2832948132418096
  rhythmicContrast: 0.7801632201299071
purpose: []
